<?php

namespace ContainerXvfyuOo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getR310ControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mQcw_gM.App\Controller\R310Controller::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mQcw_gM.App\\Controller\\R310Controller::register()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'passwordEncoder' => ['privates', '.errored.HEp9yWl', NULL, 'Cannot determine controller argument for "App\\Controller\\R310Controller::register()": the $passwordEncoder argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'passwordEncoder' => '?',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\R310Controller::register()', $container);
    }
}
