<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNExTmt3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNExTmt3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNExTmt3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNExTmt3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNExTmt3\App_KernelDevDebugContainer([
    'container.build_hash' => 'NExTmt3',
    'container.build_id' => '7d41bbe1',
    'container.build_time' => 1738155556,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNExTmt3');
