<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMYeeJ6z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMYeeJ6z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMYeeJ6z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMYeeJ6z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMYeeJ6z\App_KernelDevDebugContainer([
    'container.build_hash' => 'MYeeJ6z',
    'container.build_id' => 'dc6c67c3',
    'container.build_time' => 1738099859,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMYeeJ6z');
