<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvfyuOo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvfyuOo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXvfyuOo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXvfyuOo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXvfyuOo\App_KernelDevDebugContainer([
    'container.build_hash' => 'XvfyuOo',
    'container.build_id' => '3d606e39',
    'container.build_time' => 1738153910,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvfyuOo');
